repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-docstring-first
    -   id: check-json
        exclude: ^cli/.vscode/
    # -   id: check-yaml
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-python-jose, types-requests]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
# -   repo: local
#     hooks:
#     -   id: test-check
#         name: test-check
#         entry: ./run_tests.sh
#         language: system
#         pass_filenames: false
#         always_run: true
