"""add campaign column

Revision ID: 16b6513f58b3
Revises: bf89559d7f8a
Create Date: 2025-04-25 13:06:08.009703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b6513f58b3'
down_revision: Union[str, None] = 'bf89559d7f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_tasks', sa.Column('campaign', sa.String(), nullable=True))
    op.create_index(op.f('ix_label_tasks_campaign'), 'label_tasks', ['campaign'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_tasks_campaign'), table_name='label_tasks')
    op.drop_column('label_tasks', 'campaign')
    # ### end Alembic commands ###
