"""blacklit add reviewed column

Revision ID: 88f06b5a6565
Revises: 5496e5237c0c
Create Date: 2025-02-28 11:39:11.733510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f06b5a6565'
down_revision: Union[str, None] = '5496e5237c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skipped_tasks', sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skipped_tasks', 'reviewed')
    # ### end Alembic commands ###
