"""fmc blacklist use checksum instead of id

Revision ID: bf89559d7f8a
Revises: ffbba1cf3f31
Create Date: 2025-03-17 16:00:05.555976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf89559d7f8a'
down_revision: Union[str, None] = 'ffbba1cf3f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fmc_blacklist', sa.Column('measurement_checksum', sa.String(), nullable=False))
    op.drop_index('ix_fmc_blacklist_fmc_id', table_name='fmc_blacklist')
    op.create_index(op.f('ix_fmc_blacklist_measurement_checksum'), 'fmc_blacklist', ['measurement_checksum'], unique=True)
    op.drop_column('fmc_blacklist', 'fmc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fmc_blacklist', sa.Column('fmc_id', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_fmc_blacklist_measurement_checksum'), table_name='fmc_blacklist')
    op.create_index('ix_fmc_blacklist_fmc_id', 'fmc_blacklist', ['fmc_id'], unique=1)
    op.drop_column('fmc_blacklist', 'measurement_checksum')
    # ### end Alembic commands ###
