"""add fmc blacklist table

Revision ID: ffbba1cf3f31
Revises: 4f35c295a35a
Create Date: 2025-03-17 15:52:06.780617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbba1cf3f31'
down_revision: Union[str, None] = '4f35c295a35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    from sqlalchemy import inspect
    from alembic import context
    
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'fmc_blacklist' not in tables:
        op.create_table('fmc_blacklist',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fmc_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_fmc_blacklist_fmc_id'), 'fmc_blacklist', ['fmc_id'], unique=True)
        op.create_index(op.f('ix_fmc_blacklist_id'), 'fmc_blacklist', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fmc_blacklist_id'), table_name='fmc_blacklist')
    op.drop_index(op.f('ix_fmc_blacklist_fmc_id'), table_name='fmc_blacklist')
    op.drop_table('fmc_blacklist')
    # ### end Alembic commands ###
